### ISSUE TITLE
Error on `cd build` on line 50 in deploy.sh

### ISSUE THREAD

**Issue by gardinermichael** [linchpin/action-wpengine-deploy#1]
Hi there,

First off, thank you for this action -- I'm attempting to deploy to WPEngine and it's been a godsend.

To start things off, here is my yml file:

```
# Basic workflow that is manually triggered

name: Manual workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: clone
      
    - name: Install Yarn Dependecies
      run: yarn
      working-directory: ./clone
        
    - name: Install PHP Dependencies
      run: composer install --no-ansi --no-dev --no-interaction --optimize-autoloader --no-progress
      working-directory: ./clone
 
    - name: Build compiled files
      run: |
        yarn build
        yarn build:production
      working-directory: ./clone
        
    - name: Deploy to WP Engine
      id: wpengine_deploy
      uses: linchpin/action-wpengine-deploy@master
      env:
        PROJECT_TYPE: ${{ secrets.PROJECT_TYPE }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
        WPE_SSH_KEY_PRIVATE: ${{ secrets.WPE_SSH_KEY_PRIVATE }}
        WPE_SSH_KEY_PUBLIC: ${{ secrets.WPE_SSH_KEY_PUBLIC }}
        WPE_INSTALL: ${{ secrets.WPE_INSTALL }}
```

And here is the error that I'm getting:

<img width="633" alt="Screen Shot 2020-11-11 at 2 06 26 PM" src="https://user-images.githubusercontent.com/34581105/98853437-25b6e600-2427-11eb-9f77-07d91c0128bb.png">

I'm wondering why this line ([50](https://github.com/linchpin/action-wpengine-deploy/blob/61fa35e6a5a5f2fbd5acbbefcdc3f8a988dca1e9/deploy.sh#L50)) in deploy.sh is included:

`cd build`

I'm building the files in the theme's root directory and don't have a build folder, so that part is obvious, but I'm a bit confused as to the codeship reference in the comments above the line. I'm also not sure how to use said build folder as it was my impression that we're working in the ./clone folder.

I guess I was hoping for a little bit of clarification since I'm not sure exactly what's happening but I will fork your repo and tinker around a little bit.
